package com.dugcanlift.macrocalc.data

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Test
import java.io.File

/**
 * Checked against the browser build's own output, not against a reading of its
 * source. `/tmp/browser-parity.json` is regenerated by running the browser's
 * `loadExerciseLibrary` / `renderExercisePicker` logic over the same asset —
 * see `parity.mjs` in this commit's message — and committed here as a fixture
 * so the comparison runs without Node.
 *
 * With no history to rank by, this app's picker must return the browser's list
 * in the browser's order. Where they differ deliberately (ranking before the
 * cap) there is a test in [ExerciseLibraryTest] saying so.
 */
class ExerciseLibraryBrowserParityTest {

    private val library: List<LibraryExercise> by lazy {
        parseExerciseLibrary(File("src/main/assets/$EXERCISE_LIBRARY_ASSET").readText())
    }

    private val browser: JSONObject by lazy {
        JSONObject(File("src/test/fixtures/browser-parity.json").readText())
    }

    private fun expected(key: String): List<String> {
        val array = browser.getJSONArray(key)
        return (0 until array.length()).map { array.getString(it) }
    }

    private fun actual(query: String, equipment: String = "") =
        searchExerciseLibrary(library, query, equipmentFilter = equipment).map { it.name }

    @Test fun `the same file parses to the same number of exercises`() {
        assertEquals(browser.getInt("count"), library.size)
    }

    @Test fun `a name search returns the browser's rows in the browser's order`() {
        assertEquals(expected("bench"), actual("bench press"))
    }

    @Test fun `a muscle search matches the browser`() {
        assertEquals(expected("hamstrings"), actual("hamstrings"))
    }

    @Test fun `a filtered search matches the browser`() {
        assertEquals(expected("pressDumbbell"), actual("press", "dumbbell"))
    }

    @Test fun `an empty query matches the browser, cap included`() {
        assertEquals(expected("empty"), actual(""))
    }

    @Test fun `a search that fills the cap matches the browser`() {
        assertEquals(expected("squat"), actual("squat"))
    }

    @Test fun `every equipment value title cases the way the browser's regex does`() {
        val expected = browser.getJSONObject("equipTitleCase")
        expected.keys().forEach { raw ->
            assertEquals("titleCase('$raw')", expected.getString(raw), titleCaseAscii(raw))
        }
    }
}
